spring.application.name=PatientManage

server.port=8080

logging.level.root=INFO

# Mức log riêng cho package của bạn (chi tiết hơn)
logging.level.com.example.patientservice=DEBUG

# Pattern hiển thị trên Console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Pattern ghi vào file (nếu có dùng file)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
