spring.application.name=PatientManage

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/patient_manage
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=hung123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


spring.jpa.open-in-view=false



logging.level.root=INFO

# Mức log riêng cho package của bạn (chi tiết hơn)
logging.level.com.example.patientservice=DEBUG

# Pattern hiển thị trên Console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

